### ISSUE TITLE
Attempted to setup example project, when using commands in chat causes exception

### ISSUE THREAD

**Issue by LouisGameDev** [martmists/asynctwitch#10]
File "C:\Users\honglouis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asynctwitch\bots.py", line 758, in _tcp_echo_client
    yield from self.event_message(messageobj)
  File "C:\Users\honglouis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asynctwitch\bots.py", line 1103, in event_message
    yield from self.parse_commands(m)
  File "C:\Users\honglouis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asynctwitch\bots.py", line 1127, in parse_commands
    yield from self.commands[w].run(rm)
  File "C:\Users\honglouis\AppData\Local\Programs\Python\Python36-32\lib\site-packages\asynctwitch\dataclasses.py", line 510, in run
    if self.has != '':
AttributeError: 'Command' object has no attribute 'has'

# Steps to Recreate:
1. Setup Example project in README.md
2. Start bot
3. use !example in chat

Python Version: 3.6

**Comment by LouisGameDev** [comment]
Further attempts to fix this in dataclasses.py reveals more missing object attributes. Is CommandBot deprecated?

**Comment by LouisGameDev** [comment]
Bot class doesn't work in Python 3.6, switch to Python 3.5 fixes issues
